{% set name = "mdx_gh_links" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdx_gh_links-{{ version }}.tar.gz
  sha256: 434f81388fa16f3c16d54cfd32aaed6f584bd7a9c1886ffc626315d562f2e4f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=3.0.0
    - python >=3.6

test:
  imports:
    - mdx_gh_links
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Python-Markdown/github-links/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension to Python-Markdown which adds support for shorthand links to GitHub users, repositories, issues and commits.

extra:
  recipe-maintainers:
    - ocefpaf
