{% set version = "0.3" %}

package:
  name: mdx_gh_links
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mdx_gh_links/mdx_gh_links-{{ version }}.tar.gz
  sha256: 434f81388fa16f3c16d54cfd32aaed6f584bd7a9c1886ffc626315d562f2e4f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - markdown >=2.6.11
  run:
    - python
    - markdown >=2.6.11

test:
  imports:
    - mdx_gh_links

about:
  home: https://github.com/Python-Markdown/github-links/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension to Python-Markdown which adds support for shorthand links to GitHub users, repositories, issues and commits.

extra:
  recipe-maintainers:
    - ocefpaf
