travis:
  secure:
    BINSTAR_TOKEN: iHXnTgE+lJ472i1Qh8M2zsHPX2tNTGpjtPLk+AaYxDatMZzUSqAl+l3k/aXQtE+SmFps7Ocb/8j6bOGlJ9u9b20GP6pgqJPsVoyObhy4vu+fypNMu7m+IGC6CN6314PZsVkMpqT9HzVSHT9LcCv1X81CvL4P/zIBfSCFHdx6HgvBGDI5+rAyrpRCL4/3uO1sBBGHUMo7BDl6I3sQR6khtua3sSaTT8raVdqladmqwSWB+IBbIlGS14OCRexjuT0Xh7k6ZbO4LDh+eRyRnhSdmwDx8Nj4HFltxY84/a/cEmgydTcUUarPfpsdNA8ZsS7p7gFiUEFUoeT9+2kKsKQ5embX7jFXtqubNtuaKUxSNjh2/0XDgc1Z5RGyKVuwAwj74x23LylEO9AiAKQ9jHp3P+6CDpF33hkCI7LM+alrxdA98KXI3aJpTq62sE6PI4M3xD+sL9fbsYl6iGRT+3zjRH0CrcPnDQ5Bo591CcLthBzW9atbNlYjnRDQgkoKTtNJvADRyUoamXJswMcrvzQDAP8a5lzjePUKlmtZeDcJ0/jI4bquPUufZOjTVrZpvFxx7IyklJEFp7Le9mSgzxkbGZY5MS/t7EPDLqP6Ut30sCAv7PDs1CZ3kHQBp8UW882HsViDmHGF/sIehNrX1LiQItzO8PK5GOBVPawas6XmGiI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
