travis:
  secure:
    BINSTAR_TOKEN: fv3gZcGxX7MjvHX3aLA8v3vk9AvY2MdrzCH+hFdnQTgzftmGaL99/mKt4iLPmI4CFhVw3zt+RJc7TupL3jQ/xCi6ntvzjJflR/6Wnk5otFXgm6zfP1KV7jTXRjOBw6cUohyt0zZl2kAp0SOpRnzTyED83u/NHdfPJzYIhYI9nom953fGBWiap24kzxdJwYZmSbanK7Epim2ClnRg9e17fmqtxZ1m3aBSeWyfvyj6I+l3G9pXyjyc7d9Q2zUg+vmKm8+UZlxrtZDv1/jq96T1IpWYaCiFWvoh41ie91tisBb0GKymv+MfqZJes6Qry0/WUK6g9B3WcS5I3pMFqouPjtfaen1glCXP+KqCZX6Ma8QusZ5SpWHLM0fD/Hba8VxTYtObJEdJgRBz5Uj6hfLREl5Tz/afSB0/XxMeRtdqCVd/azPLAxUlRI5clRiAGDXcZWlyttI2Q6Qn9OqXYXniirOCqnu+PEUi/TBOJC+//La7n0APMaalidXhxIxZoeEuK18bDzwhpRXahKCORp6/R0Fgy5CEMhdL4FOBbLe51Oj68wycAub6RqleWyOeY8U5WetmWJ+v4JqvxKn8LcnsByvdF3Q20zLeJiM8UJArDLOT1JyNl0TYbtoDd4dzZ+aIh/Tz5Npl6QP/gszqllzQkgQ9jNmZMsq/yGEdYy0G6Q4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
